### ISSUE TITLE
Wikit 词典格式提案

### ISSUE THREAD

**Issue by ikey4u** [ikey4u/wikit#5]
wikit.db: sqlite 格式

      一共三列, 如下所示

          key, value_offset, value_size

      这里的 key 必须是唯一的不能重复的, 其值可以是单词, 图片名称, 音频名称,
      value_offset 和 value_size 分别表示对应值在 wikit.data 中的偏移地址和大小,
      比如当 key 为单词时, value_offset 就表示其释义在 wikit.data 中的偏移地址以及释义长度,
      当 key 为图片名称时, value_offset 就表示图片在 wikit.data 中的偏移地址及图片大小.

  wikit.cache: 用户查询缓存, 也就是 wikit.db 的一个子集

  wikit.data: binary

      meanings[0], meanings[1], ...
      imagns[0], images[1], ...
      audios[0], audios[1], ...

**Comment by rainhear** [comment]
- 現有的 `MDict` 源碼—— `txt` 文件編寫時，語法受限不少，代碼複用率偏低。

- 請教全新詞典格式標準中，在 `源碼` 編寫場景，能否引入類 `YAML` 語言的 `__include` 和 `__patch` 指令，

- 藉此提高代碼複用性，作者在 `源碼` 編寫完畢後，再使用 `打包工具` 編譯部署，生成平臺可調用的 `詞典` 文件格式。

``` yaml
PageDemo:
  text: Demo
  image: Demo.png

Abc:
  __include: /PageDemo

Def:
  __include: /PageDemo
  __patch:
    text: [ Def, Demo ]
```
